

# #eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJSYW1lc2giLCJlbWFpbCI6Imxpa2VqZTUwNjRAamFkc3lzLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEJHTVU0V0Jib2NJUUJsbkpsVVBncy4uTjBSa0ZEOEhiNXhTR3psdHZ6S04uWWJiTzk5VzdTIn0sIm90cCI6ODc0MjIsImlhdCI6MTcxNzgxMTIzMiwiZXhwIjoxNzE3ODE0ODMyfQ.7FP6VROI33jq4Q6Y-XTlw6ag0sqcnC4jN-Z1FRaqAl4
# POST http://localhost:5000/api/user/register
# Content-Type: application/json

# {
#     "name":"Ramesh123",
#     "email":"forera2858@eqvox.com",
#     "password":"ramesh@123"
# }

# 50186
# POST http://localhost:5000/api/user/verify
# Content-Type: application/json

# {
#     "otp":"50186",
#     "activationToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFtZXNoMTIzIiwiZW1haWwiOiJmb3JlcmEyODU4QGVxdm94LmNvbSIsIm90cCI6IjUwMTg2IiwiaWF0IjoxNzE4MzM0MDM2LCJleHAiOjE3MTg0MjA0MzZ9.jrqnE7tugC1l1flwRhkCMV9RgOYKOYGDGqAg8B7i40Q"
# }

# POST http://localhost:5000/api/user/resendOtp
# Content-Type: application/json

# {
#     "email":"soholol731@jadsys.com"
# }


# POST http://localhost:5000/api/user/login
# Content-Type: application/json

# {
#     "email":"soholol731@jadsys.com",
#     "password":"ramesh@12"
# }

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYzZGM4M2M4NTkxNmNjZTBmZGFmMGYiLCJpYXQiOjE3MTc4MjU5NzIsImV4cCI6MTcxNzk5ODc3Mn0.uVsf6N_feSauZuU4PvEtGgHWNXiz65db8M1ZhsSAjgU




# GET http://localhost:5000/api/stats
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYzZGM4M2M4NTkxNmNjZTBmZGFmMGYiLCJpYXQiOjE3MTc5MjQ5MjIsImV4cCI6MTcxODA5NzcyMn0.zIkC0I-PbMWrANH8ol-ThrMS2rRkA0FcOgCpUevE3Pw


# GET http://localhost:5000/api/user/userprofile
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYzZGM4M2M4NTkxNmNjZTBmZGFmMGYiLCJpYXQiOjE3MTgyNjIxMzksImV4cCI6MTcxODQzNDkzOX0.qGxkslCVJ75eIo63y6FMhSEPtRIisL8BbMBDy4mGSTM












# POST http://localhost:5000/course/checkout/6666b453897c7fab5c893e07
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYzZGM4M2M4NTkxNmNjZTBmZGFmMGYiLCJpYXQiOjE3MTc5MjQ5MjIsImV4cCI6MTcxODA5NzcyMn0.zIkC0I-PbMWrANH8ol-ThrMS2rRkA0FcOgCpUevE3Pw

# {
#   "user_id": "6663dc83c85916cce0fdaf0f"  // Replace with an actual user ID
# }